Product overview of all products
AgoraDoc/dita-guide-reuse pull request #10
Opened 2021-11-02 09:12 UTC by Cilla-luodan

The table format in output markdown file is a mess, need more editing.

2021-11-11 11:13 UTC, wangjie-agora commented on RTC/_Product-Overview.ditamap
> +    <topichead navtitle="Product Overview">
这个应该分别更新到 Video 和 Live 的 ditamap 里，文档是以一个产品的一个平台为单位发布的，output 的配置文件也不需要新增了。

2021-11-12 03:21 UTC, Cilla-luodan commented on RTC/_Product-Overview.ditamap
> +    <topichead navtitle="Product Overview">
OK，已修改。

2021-11-17 10:28 UTC, wangjie-agora requested changes
- 句子中间不能换行，要处理一下
- 产品概述的 md topic 文件名建议加上 product- 前缀，便于区分

2021-11-17 10:28 UTC, wangjie-agora commented on RTC/_Video.ditamap
> +            <topicref href="solution-comparison.md" format="markdown" toc="no" props="live lives"/>
这个 topicref 不适用于视频通话，直接删掉就行了

2021-11-17 10:45 UTC, wangjie-agora commented on RTC/conref/product-overview-introduction.dita
> +                    <colspec colnum="3" colname="col3"/>
这一列加 props 设置仅音频、视频、互动直播有

2021-11-22 09:09 UTC, Cilla-luodan commented on RTC/conref/product-overview-introduction.dita
> +                    <colspec colnum="3" colname="col3"/>
dita 的规则是不能对列做条件化输出，刚才试了下，加了props后，整个表都发不出来。

2021-11-22 09:52 UTC, Cilla-luodan commented on RTC/conref/product-overview-introduction.dita
> +            <note props="lives">
这么处理是因为要共用function表格，note直接包含在表格下面的p标记对里了，用条件化发布直接发出来，方便做同源。

2021-11-23 06:26 UTC, wangjie-agora approved these changes

2021-11-23 06:26 UTC, merged